name: Build and Diagnostic Pipeline - Henrique

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'teste-build'

jobs:
# Build o projeto via gradle
  build-gradle:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Realizar o checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Criando Cache no Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Tornando o gradlew execut치vel
        run: chmod +x ./gradlew
      
      - name: Executando a Build no Projeto
        run: ./gradlew build
# Testa o projeto via Gradle
  test-gradle:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - name: Realizar o checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Tornando o gradlew execut치vel
        run: chmod +x ./gradlew

      - name: Rodando os Testes
        run: ./gradlew test --info

      - name: Realizando Upload dos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: Resultados do Teste
          path: '**/build/test-results/**/*.xml'
