name: Pipeline de Build - Henrique

on:
  push:
    branches:
      - 'master' # Monitorar todas as branches

jobs:
  build:
    name: Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Realizar o checkout do código
        uses: actions/checkout@v3

      - name: Configurando JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Criando Cache no Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Tornando o gradlew executável
        run: chmod +x ./gradlew
      
      - name: Executando a Build no Projeto
        run: ./gradlew build

      - name: Rodando os Testes
        run: ./gradlew test
